apiVersion: v1
kind: Service
metadata:
  name: http-server-service
  namespace: k8s-basics
spec:
  type: LoadBalancer

  selector:
    app: http-server

  ports:
    - port: 4000
      targetPort: 4000
