name: CI - HTTP Server

on:
  push:
    paths:
      - "http-server/**"
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3 Build Docker Image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./http-server
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/http-server:${{github.sha}}
